### ISSUE TITLE
Roadmap

### ISSUE THREAD

**Issue by HugoJacq** [HugoJacq/ABL_response_to_SST_front#1]
- [x] write README
- [x] upload  data to zenodo
- [x] fill metadata on zenodo
- [x] provide user modification
- [x] organize python script
- [x] provide python scripts
- [x] test the workflow on two computers

**Comment by HugoJacq** [comment]
done, I close.
